---
language: go
go_import_path: github.com/piotrpersona
before_deploy:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - ./build.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $GOPATH/bin/httpst-*
  skip_cleanup: true
  on:
    tags: true
